ai-robots-txt/ai.robots.txt

robots.txt
Used by Google to crawl for internal research and development. It’s unknown what exactly this entails, but is a generic user agent that is used when no other appropriate user agent is available. Documentation available from Google: https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers
=> Add GoogleOther

robots.txt
I couldn’t seem to find evidence these bots are AI-related from their descriptions, nor are they so tagged over at Dark Visitors. They appear to be here for other reasons. Perhaps holdovers from a general-purpose `robots.txt`?
https://awario.com/bots.html
https://www.brandwatch.com/legal/magpie-crawler/
https://www.meltwater.com/en/products/media-monitoring
https://www.scoop.it/wp-static-pages/bots/
https://pipl.com/bot
=> Remove potential false positives

robots.txt
`PetalBot` has been crawling very aggressively for some time and flouting `robots.txt` to boot. It’s finally made it to Cloudflare’s [verified AI bots category](https://radar.cloudflare.com/traffic/verified-bots), so I figure it’s time we added it too.
I’m also adding `facebookexternalhit` from #21 since it behaves exactly like `meta-externalagent`. There may be concerns that doing so would affect linking on FB, but that’s probably the very reason Meta is repurposing this particular UA for AI crawling – to prevent it being blocked as an AI bot. It’s your call when we should include this one.
=> Add `PetalBot` (and `facebookexternalhit`?)

robots.json
[ICC-Crawler](https://ucri.nict.go.jp/en/icccrawler.html) is a crawler operated by NICT, a Japanese independent administrative agency. Its operation policy was revised on July 11, 2024, adding the following to the purpose of data collection:
- Use the collected data for artificial intelligence technologies.
- Provide data to third parties, including commercial companies.
- Those companies can use the data for their own business.
This change was made in accordance with the Japanese government's AI policy. The government wants to support domestic IT companies to develop home-grown AI foundation models in Japan.
=> Add ICC-Crawler

FAQ.md
Cloudflare now offers to block AI scrapers automatically, including ones which don't respect robots.txt.
=> Add Cloudflares first-party scraper blocking to FAQ

.github/workflows/main.yml
This should avoid failed/unnecessary workflow runs when content *other* than `robots.json` gets updated (readme, faq, etc).
=> only build on changes to robots.json

.github/workflows/main.yml
Currently, because the main workflow first removes the old files before committing new ones, the files are shown to be replaced _in toto_ in diffs. This is unnecessary because `file_put_contents` as used in `action.php` overwrites by default when the `FILE_APPEND` flag isn’t set.
This PR removes the redundant operation and allows a proper diff to be generated.
=> Improve main workflow

.github/workflows/daily_update.yml, .github/workflows/main.yml
It seems that some delay after the scripts have run is useful. Before it happened that changes seemingly were not registered and committed from/by the actions.
=> log the diff in the update actions

.github/workflows/upload-robots-txt-file-to-release.yml
This workflow uploads the `robots.txt` file as a release artefact when a release is published. This is essentially the same as downloading the automatic `Source code (zip)` file and extracting the `robots.txt` file from there, except that this is more direct.
=> Create workflow to upload `robots.txt` file as release artefact

.github/workflows/ai_robots_update.yml, .github/workflows/main.yml, code/tests.py
My last PR #51 changed the attribution in some cases. Hence I reverted the merge of the GH Action files which restores the original attribution logic.
The work is still done with the Python. This PR does not revert to PHP.
In line with the current behaviour and contrary to pre PR #51 the main GH Action is triggered by every push to main.
--
A bit off topic is the addition of the file encoding to the tests. I believe this makes sense.
--
Update the PR link.
=> Restore attribution

robots.json
Information on the bot can be found here: https://www.semrush.com/bot/
Despite the robots.txt/user agent section, my webserver logs indicate that it only uses the `SemrushBot/7~bl` user agent, which isn't included in their list at all. (they say that the user agent would be suffixed with `-OCOB` for their AI tool, or some other suffix for their other tools' scrapers) As such, I chose to use the more general `SemrushBot` name.
I chose a ~10s frequency based on my own logs and on their indicated willingness to respect crawl-delay directives:
> [...] Our crawler can take intervals of up to 10 seconds between requests to a site. Higher values will be cut down to this 10-second limit. If no crawl-delay is specified, SemrushBot will adjust the frequency of requests to your site according to the …
=> Block SemrushBot

.github/workflows/main.yml
Before, the Action would fail in case there were no changes made to any files by the converter.
I think this behaviour is the result of the action running in more scenarios than when it was initially created.
An example of a failed Action run which should have succeeded in my understanding is this: https://github.com/ai-robots-txt/ai.robots.txt/actions/runs/12624527774/job/35174915693
=> Allow Action to succeed even if no changes were made

robots.json
Semrush has confirmed via email that the AI tools will crawl under the UA strings `SemrushBot-OCOB` and `SemrushBot-SWA`. And `SemrushBot/7~bl` is used for Backlink Analytics:
> They are not related to any AI, they just read the HTML looking for backlinks.
=> Actually block Semrush’s AI tools

README.md, code/robots.py, code/test_files/nginx-block-ai-bots.conf, code/tests.py, nginx-block-ai-bots.conf
This PR implements an export for Nginx. As htaccess files cannot be processed by the Nginx web server, the rules need to go into an Nginx configuration file. 
A new file `nginx-block-ai-bots.conf` is generated when the `robots.py` script is run. 
This file is copied to the Nginx web server config directory, such as `/etc/ngin/snippets/nginx-block-ai-bots.conf` and then included in the virtual server configuration(s), e.g.:
```
server {
listen 80;
listen [::]:80;
...
include snippets/nginx-block-ai-bots.conf;
...
}
```
=> Implement Nginx configuration snippet export

robots.json
This adds the `imgproxy` crawler associated with [imgproxy](https://imgproxy.net).
> "World’s fastest AI-powered self-hosted image processing server."
Whether it respects `robots.txt` is unclear as the crawler is not documented on the linked site. Given that and its association with/usage of AI I'd like to include it in the file and support blocking it via `.htaccess` and any other methods we include going forward.
Thanks to Brian at Skewray Research for highlighting this one.
=> chore(robots.json): adds imgproxy crawler

code/robots.py
Dark Visitors have added a new category for "AI Agents", seperate from "AI Assistants". They are functionally similar and we already block the latter, so the former should probably be included as well.
https://darkvisitors.com/agents
=> Include "AI Agents" from Dark Visitors

robots.json
Updated list with five new proposed AI bots:
User-agent: aiHitBot
User-agent: Cotoyogi
User-agent: Factset_spyderbot
User-agent: FirecrawlAgent
User-agent: TikTokSpider
aiHitBot:
https://www.aihitdata.com/about
"aiHitdata is a massive, artificial intelligence/machine learning, automated system"
Cotoyogi:
https://ds.rois.ac.jp/en_center8/en_crawler/
AI LLM scraper, more info (in Japanese): https://ds.rois.ac.jp/center8/
Factset_spyderbot:
https://www.factset.com/ai
Cloudflare also lists as a Verified AI bot: https://radar.cloudflare.com/bots#verified-bots
FirecrawlAgent:
https://www.firecrawl.dev/
AI LLM scraper: "Firecrawl turns entire websites into clean, LLM-ready markdown or structured data. Scrape, crawl and extract the web with a single API. Ideal for AI companies looking to empower …
=> AI bots to consider adding

robots.json
My logger indicated multiple robots.txt violations from `meta-externalagent`. Looking into their site, it seemed like they intended for it to respect it, but the user agent Meta shows in the sample robots.txt shows a lowercase user agent, as well as their actual user agent being lowercase. I suspect that their crawler is case sensitive when looking at robots.txt.
Also, there was a period after "Yes" which is inconsistent with the rest of the robots.json file.
=> Fixed meta-external* being titlecase, and removed period for consistency

.github/workflows/run-tests.yml
As seen in #123 , it is possible for invalid JSON to be pushed to robots.json, which can cause exceptions elsewhere in the project or in downstream projects.
The existing python tests do not reference the robots.json in the root of the project, but rather a different one at `code/test_files/robots.json`, since they appear to be testing the generation code rather than the source data
This PR adds a simple JSON lint job using JQ to run in parallel with the python tests. This provides feedback on PRs if the JSON is valid or not, and will provide details of what is malformatted in the job log.
A failed run example can be found here: https://github.com/holysoles/ai.robots.txt/actions/runs/15049903349/job/42301866816
=> lint robots.json during pull requests

robots.json
This adds the `Google-CloudVertexBot` crawler. Pertinent JSON is here:
```json
"Google-CloudVertexBot": {
"operator": "Google",
"respect": "[Yes](https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers)",
"function": "Build and manage AI models for businesses employing Vertex AI",
"frequency": "No information.",
"description": "Google-CloudVertexBot crawls sites on the site owners' request when building Vertex AI Agents."
}
```
=> chore(robots.json): adds Google-CloudVertexBot

docs/additional-steps/bing.md
I think it might be worth to also mention the X-Robots-Tag for Bing since setting the HTTP Header might be easier then including the meta tags on all pages in some setups.
=> Mention X-Robots-Tag header as alternative for bing

robots.json
This adds the crawler operated by [Mistral AI](https://docs.mistral.ai/robots/). Pertinent JSON is here:
```json
"MistralAI-User/1.0": {
"operator": "Mistral AI",
"function": "Takes action based on user prompts.",
"frequency": "Only when prompted by a user.",
"description": "MistralAI-User is for user actions in LeChat. When users ask LeChat a question, it may visit a web page to help answer and include a link to the source in its response.",
"respect": "Yes",
},
```
=> chore(robots.json): adds MistralAI-User/1.0 crawler

robots.json
Adds support for `wpbot`. Pertinent portion of the updated JSON:
```json
"wpbot": {
"operator": "[QuantumCloud](https://www.quantumcloud.com)",
"respect": "Unclear at this time; opt out provided via [Google Form](https://forms.gle/ajBaxygz9jSR8p8G9)",
"function": "Live chat support and lead generation.",
"frequency": "Unclear at this time.",
"description": "wpbot is a used to support the functionality of the AI Chatbot for WordPress plugin. It supports the use of customer models, data collection and customer support."
},
```
Reported by Brian Sutin at Skewray Research: ` [12/May/2025:08:15:46 +0000] "GET / HTTP/2" 401 52 "-" "Mozilla/5.0 (compatible; wpbot/1.3; +https://forms.gle/ajBaxygz9jSR8p8G9)"
https://wordpress.org/plugins/chatbot/`
=> chore(robots.json): adds wpbot

robots.json
=> Add AndiBot and PhindBot

.github/workflows/ai_robots_update.yml
Replaced `--staged` flag with `--cached` (the former is an alias for the latter). Stages files for commit and then checks if there's anything staged instead of using two separate checks. Checks for staged changes and skips if there aren't any.
Verified/tested in https://github.com/ai-robots-txt/ai.robots.txt/pull/138.
=> chore(ai_robots_update.yml): correct workflow by revising git flags + adding guard

robots.json
Based on [this comment](https://github.com/ai-robots-txt/ai.robots.txt/issues/40#issuecomment-2524591313) and subsequent ones, and comments in #21, it appears that `facebookexternalhit` may be being repurposed beyond its [stated use](https://developers.facebook.com/docs/sharing/webmasters/web-crawlers/): "to crawl the content of an app or website that was shared on one of Meta’s family of apps… ".
This PR re-adds `facebookexternalhit`, labels as untrusted, and includes a note that blocking it will break OpenGraph sharing in social media and rich links in Apple's Messages app, as discussed in #40.
=> re-add facebookexternalhit

robots.json
@glyn mentioned https://github.com/ai-robots-txt/ai.robots.txt/pull/73#issuecomment-2618570717 and asked why Semrush stated that SemrushBot-SWA is for AI. So I looked it up and SWA stands for SEO Writing Assistant: https://www.semrush.com/swa/. Like similar writing assistants, it’s using AI to make suggestions. (In a previous iteration, it was actually called [AI Writing Assistant](https://www.semrush.com/apps/ai-writing-assistant/).)
This PR updates function and description for the two known AI bots from Semrush.
If there’s any lingering concerns about the other UA strings, please air them below and let’s confront the company directly.
https://www.semrush.com/bot/
=> Update funtion and description for SemrushBot

robots.json
This adds the `OpenAI` user agent, reported by Brian at Skewray Research after being observed in logs.
=> chore: adds OpenAI but user agent

robots.json
This adds the `Google-Firebase` and `ShapBot` user agents, reported by Brian at Skewray Research after being observed in logs.
=> chore: add Google-Firebase and ShapBot

robots.json
- Update Brightbot operator to https://brightdata.com/brightbot.
- Change Brightbot frequency to "At least one per minute."
- Expand Brightbot description with disguise tactics link.
- Add new entry for meta-webindexer under Meta operator.
- Set meta-webindexer respect to "Unclear at this time."
- Define meta-webindexer function as "AI Assistants."
- Set meta-webindexer frequency to "Unhinged, more than 1 per second."
- Include meta-webindexer description on improving Meta AI search.
=> Update Brightbot operator and details; add meta-webindexer entry

README.md
[Really Simple Licensing](https://rslstandard.org/) is an open standard that helps publishers license their content to AI companies from `robots.txt`: https://rslstandard.org/guide/robots-txt
This PR adds information about this newer option to README.md.
=> Add information about Really Simple Licensing standard
