README.md
table-of-bot-metrics.md

A table to offer more detail on each crawler and to incentivise bot operators to behave considerately.

Adds table of bot details and metrics

---

table-of-bot-metrics.md

Reference: https://g.co/gemini/share/5bef4db5f87d

Add Google Gemini response on AbsBot-Google for bot metrics table.

---

table-of-bot-metrics.md

Fix Markdown in `table-of-bot-metrics.md`

---

robots.txt

Per [Apple's docs](https://support.apple.com/en-us/119829#datausage) ([via Matthew Bogart](https://matthewbogart.com/@matt/112605297864483766))

Block Applebot-Extended

---

FAQ.md

These are mostly sourced from `README.md`, but grouped by technology for ease of use. In the case of Apache httpd, a note is added on how to optimise the setup.

Add last line of defence to FAQ

---

robots.json

https://imagesift.com/about
They say to put `ImagesiftBot` in robots.txt

Fix Imagesift user agent

---

README.md

This covers the corresponding reporting mechanism for #28. A link to our growing FAQ is also added.

Add links for reporting and FAQ to README.md

---

FAQ.md

Adding link to https://vercel.com/templates/firewall/block-ai-bots-firewall-rule

Add instructions for AI bot blocking on Vercel

---

README.md

A detailed blogpost to - See the live dashboard showing the websites that are blocking AI Bots such as GPTBot, CCBot, Google-extended and ByteSpider from crawling and scraping the content on their website. Learn which AI crawlers / scrapers do what and how to block them using Robots.txt.

Add an additional resource - README.md

---

code/dark_visitors.py

Sort the content of robots.json by keys, case-insensitively

---

FAQ.md

* Order the FAQ more sensibly
* Expand the "why?" FAQ

Update the FAQ

---

FAQ.md

I deleted the point about excessive load on crawled sites as any other crawler could potentially be guilty of this and I wouldn't want our scope to creep to all crawlers.
I added environmental impact, which was always in the front of my mind when contributing to this site.
Ref: https://github.com/ai-robots-txt/ai.robots.txt/issues/53#issuecomment-2466042550

Clarify our rationale

---

.github/workflows/main.yml

Ref: https://github.com/ai-robots-txt/ai.robots.txt/issues/60#issuecomment-2571437913
Ref: https://stackoverflow.com/questions/11783875/importerror-no-module-named-bs4-beautifulsoup

Ensure dependency installed

---

.github/workflows/main.yml

Specifically, when github workflows or code is changed as either of these can affect the conversion results.
Ref: https://github.com/ai-robots-txt/ai.robots.txt/issues/60

Convert robots.json more frequently

---

.htaccess
README.md
code/robots.py
code/test_files/.htaccess
code/tests.py

This should work to solve #64
I added also a test function in `code/tests.py`.
I tried to run Pytest and it seems to work.
Tell me if I can make the implementation better in any way, and thanks for your project

Implementing automatic htaccess generation

---

README.md

This PR includes a suggested update for the project README.md file. I think this could be helpful for people who make use of Cloudflare WAF rules that trigger based on the cf.bot_management.verified_bot condition.
Thank you for creating this project, I really appreciate it.

List of AI bots Cloudflare considers "Verified"

---

.github/workflows/run-tests.yml

Automatically run tests on pull requests or push to main.
Depends on #80.
Closes #82.

Add run-tests workflow

---

README.md

Also, remove comment from tests.py to avoid
duplicate maintenance.
Fixes: https://github.com/ai-robots-txt/ai.robots.txt/issues/81

Document testing in README

---

robots.json

Update based on perplexity bot docs
Fix issue #90

Update perplexity bots

---

FAQ.md

Some firms, including those with .ai domains, have offered to sponsor this project. So make our position clear.

Clarify our position on sponsorship

---

README.md
docs/additional-steps/bing.md

> Proposal for a Bing document detailing additional steps required to opt-out of AI training, rather than the potentially drastic action of blocking bingbot in robots.txt
An update to [#114](https://github.com/ai-robots-txt/ai.robots.txt/pull/114) via [dennislee1](https://github.com/dennislee1)
@glyn

Bing AI opt-out instructions

---

README.md

Add Traefik plugin to the README.md file

---

robots.json

This adds the crawler operated by [Qualified](https://www.qualified.com). Pertinent JSON is here:
```json
"QualifiedBot": {
"description": "Operated by Qualified as part of their suite of AI product offerings.",
"frequency": "No explicit frequency provided.",
"function": "Unclear, but operator AI agents and other related products; usage can be assumed to support said products.",
"operator": "[Qualified](https://www.qualified.com)",
"respect": "Unclear at this time.",
},
```

chore(robots.json): adds QualifiedBot crawler

---

README.md

This seeks to address https://github.com/ai-robots-txt/ai.robots.txt/issues/127 by clarifying the types of agents that we block and providing guidance to users to reference the table of bot metrics featured in the project.
This would also address https://github.com/ai-robots-txt/ai.robots.txt/issues/53.

chore(README): updates the opening line of our README to clarify the types of agents we block

---

robots.json

Adds support for `EchoboxBot`.

chore(robots.json): adds EchoboxBot

---

robots.json

Adds a number of new `SemrushBot` agents.

chore(robots.json): adds additional SemrushBot user agents

---

robots.json

Update with Poseidon Research Crawler as found in nytimes.com/robots.txt

Update robots.json with new crawler
